// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbqedhkdylkznyqfehwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicWVkaGtkeWxrem55cWZlaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMTkwNDEsImV4cCI6MjA1NDU5NTA0MX0.tYfZYRWLC0i4mUKjwvrOF3LzqvIe86_jG7KBCtEbQ6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);